### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by JerryGibbes** [datatypevoid/vulgar#2]
**I'm submitting a issue when installing **

running latest node version and npm
------------------

Cloning into 'mean2'...

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: You don't seem to have a generator with the name vulgar:config installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 37 registered generators run yo with the `--help` option.
    at Environment.create (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\yeoman-environment\lib\environment.js:296:7)
    at Environment.run (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\yeoman-environment\lib\environment.js:364:24)
    at E:\Soft & Tools\nodejs\node_modules\vulgar-cli\lib\install.js:95:9
    at Environment.resolver.lookup (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at generateConfigObject (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\lib\install.js:94:7)
    at Array.<anonymous> (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\lib\install.js:35:7)
    at handleItem (E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\async-series\index.js:14:13)
    at E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\async-series\index.js:16:36
    at E:\Soft & Tools\nodejs\node_modules\vulgar-cli\lib\install.js:212:5
    at E:\Soft & Tools\nodejs\node_modules\vulgar-cli\node_modules\shelljs\src\exec.js:107:7

**Comment by datatypevoid** [comment]
Hi there! First things first, have you installed the global dependency of `generator-vulgar`? If not you can install it with:

```bash
$ npm install -g generator-vulgar
```

**Comment by JerryGibbes** [comment]
hi, this solved the installing issue. good job.

but i dont believe i saw that in the read me. i will close the issue

**Comment by datatypevoid** [comment]
You are absolutely correct. It should be but somehow fell out of the docs recently. Thanks again!
