### ISSUE TITLE
Bug creating an app

### ISSUE THREAD

**Issue by erperejildo** [datatypevoid/vulgar#24]
When I run `vulgar init name` I get this error after provide my username and the terminal stucks in that line:
https://dl2.pushbulletusercontent.com/hd7xHF6UVmk94pK7XFPY1RhR0QecZT0M/Sin%20t%C3%ADtulo.jpg

Edit: this problem is just on Windows. No faced on Mac

**Comment by erperejildo** [comment]
If I create the project with no initial config after install typings webpack webpack-dev-server concurrently
and run npm install I run npm start and gulp serve or npm server (I tried both but I'm not sure which one is the correct one) in other terminal (without close the previous one) and I get this other bug:

```
Node environment set for development
No value set for MONGO_URI...
Using the supplied value from config object...
MONGO_URI set for development
Wizardry is afoot on port 3000
Mongoose default connection to development database disconnected

C:\Users\Casa\Desktop\MEAN2\node_modules\mongodb\lib\server.js:261
        process.nextTick(function() { throw err; })
                                      ^
 MongoError: failed to connect to server [localhost:27017] on first connect
    at [object Object].<anonymous> (C:\Users\Casa\Desktop\MEAN2\node_modules\mon
godb-core\lib\topologies\server.js:313:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (C:\Users\Casa\Desktop\MEAN2\node_modules\mon
godb-core\lib\connection\pool.js:260:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (C:\Users\Casa\Desktop\MEAN2\node_modules\mongodb-core
\lib\connection\connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 [20:26:50] [nodemon] app crashed - waiting for file changes before starting...
```

Is it because I did not create this initial config?

**Comment by datatypevoid** [comment]
Have you managed to clear this error up?

**Comment by erperejildo** [comment]
It's related with mongodb, not with vulgar. I have to figure out how to fix it on Windows but at least works with Mac
