### ISSUE TITLE
Typings Error: Unknown Dependancy

### ISSUE THREAD

**Issue by georgeedwards** [datatypevoid/vulgar#3]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)

- **I'm submitting a ... **

  [*] bug report

  [ ] feature request

  [ ] question about the decisions made in the repository

- **What is the current behavior?**
Typings Install is failing because of an Unknown Dependancy
```
C:\Users\George\vulgar-trial\Gas-Sense>typings install
typings ERR! message Unknown dependency: registry:dt/core-js#0.0.0+20160317120654

typings ERR! cwd C:\Users\George\vulgar-trial\Gas-Sense
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin\\typings-install.js"
typings ERR! node -v v5.8.0
typings ERR! typings -v 0.6.9

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- <https://plnkr.co>, <https://codepen.io>, or similar.
- **What is the expected behavior?**
Typings to install without issue.
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
Windows 10, everything else standard as you describe in the getting started steps.
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by datatypevoid** [comment]
I have successfully built and tested the framework on three separate `windows 10 x64` builds, `ubuntu 14.04`, and have other people successfully using this in their day-to-day, and none of us have this error. Can you verify this with another installation attempt, following all of the instructions in the `README`? There may have been something up elsewhere in the Internets disturbing the process. In the mean time,I am going to close this issue, and if you encounter the same error, please reopen the issue.

**Comment by georgeedwards** [comment]
@datatypevoid OK, maybe I can try and help with the documentation when I track down the issue. 

Firstly, when following the quick start steps, the script to set up an admin user fails because the mongodb connection is refused. No mention in steps about starting this. In the run above, I had a MongoDB instance running anyway, so I didn't have any issues.

I ran `npm install` in a command prompt window (running as admin) and got this output:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! path C:\Users\George\Source\Repos\test\node_modules\.staging\angular2-5560b5fc
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\test\node_modules\.staging\angular2-5560b5fc' -> 'C:\Users\George\Source\Repos\test\node_modules\angular2'
npm ERR!     at destStatted (C:\Users\George\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\test\node_modules\.staging\angular2-5560b5fc' -> 'C:\Users\George\Source\Repos\test\node_modules\angular2'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\test\node_modules\.staging\angular2-5560b5fc' -> 'C:\Users\George\Source\Repos\test\node_modules\angular2'] parent: 'vulgar' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\George\Source\Repos\test\npm-debug.log
```

Any ideas what is likely to have caused this?

**Comment by georgeedwards** [comment]
Again, even if I run init with a MongoDB instance, I get this during the npm install stage:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! path C:\Users\George\Source\Repos\eval\node_modules\.staging\portfinder-c8224f06
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\eval\node_modules\.staging\portfinder-c8224f06' -> 'C:\Users\George\Source\Repos\eval\node_modules\portfinder'
npm ERR!     at whenOldMovedAway (C:\Users\George\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:43:5)
npm ERR!     at C:\Users\George\AppData\Roaming\npm\node_modules\npm\lib\utils\rename.js:13:14
npm ERR!     at CB (C:\Users\George\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:85:17)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\eval\node_modules\.staging\portfinder-c8224f06' -> 'C:\Users\George\Source\Repos\eval\node_modules\portfinder'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\George\Source\Repos\eval\node_modules\.staging\portfinder-c8224f06' -> 'C:\Users\George\Source\Repos\eval\node_modules\portfinder'] parent: 'vulgar' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\George\Source\Repos\eval\npm-debug.log


C:\Users\George\AppData\Roaming\npm\node_modules\vulgar-cli\lib\install.js:84
      throw err;
      ^
 4294963248
```

**Comment by datatypevoid** [comment]
Yeah, I suppose you're right about putting a note about starting up Mongo if you aren't using a cloud solution. I am actually surprised no one has had a problem with that yet.

Anyway, if you look at your last error towards the end, you'll see:

`npm ERR! Please try running this command again as root/Administrator.`

Could you try running the command as the root user or the Administrator and let me know if it works?

**Comment by georgeedwards** [comment]
@datatypevoid yes, but that was run as the admin user...

I thought I would try to get this running on my mac instead. I followed the quick start steps exactly. But this is what the app looks like when run:
[![enter image description here][1]][1]
I assume this is not loaded correctly? Here are some of the issues my `npm start` spits out:

```
[default] /Users/georgeedwards/Desktop/eval/node_modules/angular2/src/router/router.d.ts (147,70):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/CoreOperators.d.ts (35,67):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/CoreOperators.d.ts (50,66):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/CoreOperators.d.ts (89,67):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/CoreOperators.d.ts (94,38):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/CoreOperators.d.ts (94,50):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (46,62):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (47,42):
    Cannot find name 'Iterator'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (103,74):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (103,84):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (143,66):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (158,65):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (201,66):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (206,38):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/Observable.d.ts (206,50):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/ForkJoinObservable.d.ts (6,50):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/ForkJoinObservable.d.ts (7,58):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/FromObservable.d.ts (7,38):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/FromObservable.d.ts (7,51):
    Cannot find name 'Iterator'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/PromiseObservable.d.ts (9,31):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/node_modules/rxjs/observable/PromiseObservable.d.ts (10,26):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/src/app/app.component.ts (46,15):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/app.component.ts (92,50):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/home/home.component.ts (35,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/home/home.component.ts (37,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/rating.component.ts (17,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/recipe-details.component.ts (28,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/recipe-details.component.ts (43,34):
    Property 'assign' does not exist on type 'ObjectConstructor'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/recipe-list.component.ts (27,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/recipes.component.ts (28,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/recipes/recipes.reducer.ts (52,20):
    Property 'assign' does not exist on type 'ObjectConstructor'.
[default] /Users/georgeedwards/Desktop/eval/src/app/shared/components/accordion/accordion-group.component.ts (12,13):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/app/todo/todo.component.ts (18,15):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/main.browser.ts (18,46):
    Cannot find name 'Promise'.
[default] /Users/georgeedwards/Desktop/eval/src/main.browser.ts (45,15):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/main.browser.ts (46,36):
    Cannot find name 'module'.
[default] /Users/georgeedwards/Desktop/eval/src/polyfills.ts (11,1):
    Cannot find name 'require'.
[default] /Users/georgeedwards/Desktop/eval/src/polyfills.ts (22,3):
    Cannot find name 'require'.
```

Not sure if this is a typescript thing not working properly, or an angular thing etc. 
  [1]: http://i.stack.imgur.com/yhOuj.png

**Comment by georgeedwards** [comment]
could this be because I am using a v5 node server?

**Comment by datatypevoid** [comment]
I am also using 5.9.1 on my boxes I believe. Definitely `v5.x`. That last one looks like a `typings` issue. I will take another look at everything this evening after work. Sorry for the trouble, and thanks for sticking it out!

**Comment by datatypevoid** [comment]
The app screenshot looks fine though, so I am not sure how it is running yet you are getting errors. Can you interact with the components in the browser?

**Comment by datatypevoid** [comment]
@georgeedwards Any luck sorting it out?

**Comment by debben** [comment]
I was getting the exact same 'Cannot find name' errors. These were all resolved by running

> typings install
